2020-11-23 14:07:40,874 INFO    MainThread:38356 [wandb_setup.py:_flush():70] setting env: {}
2020-11-23 14:07:40,874 INFO    MainThread:38356 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2020-11-23 14:07:40,874 INFO    MainThread:38356 [wandb_setup.py:_flush():70] setting login settings: {}
2020-11-23 14:07:40,874 INFO    MainThread:38356 [wandb_setup.py:_flush():70] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f16604480d0>
2020-11-23 14:07:40,875 INFO    MainThread:38356 [wandb_init.py:_log_setup():303] Logging user logs to /home/namitrak/Documents/Machine Learning/Image segmentation/wandb/run-20201123_140740-2tskz5kw/logs/debug.log
2020-11-23 14:07:40,875 INFO    MainThread:38356 [wandb_init.py:_log_setup():304] Logging internal logs to /home/namitrak/Documents/Machine Learning/Image segmentation/wandb/run-20201123_140740-2tskz5kw/logs/debug-internal.log
2020-11-23 14:07:41,511 INFO    MainThread:38356 [wandb_run.py:_console_start():1218] atexit reg
2020-11-23 14:07:41,511 INFO    MainThread:38356 [wandb_run.py:_redirect():1085] redirect: SettingsConsole.WRAP
2020-11-23 14:07:41,511 INFO    MainThread:38356 [wandb_run.py:_redirect():1116] Wrapping output streams.
2020-11-23 14:07:41,511 INFO    MainThread:38356 [wandb_run.py:_redirect():1132] Redirects installed.
2020-11-23 14:07:44,210 INFO    MainThread:38356 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 14:07:44,213 INFO    MainThread:38356 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 14:08:11,006 INFO    MainThread:38356 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 14:08:11,010 INFO    MainThread:38356 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 14:08:11,137 INFO    MainThread:38356 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 14:08:11,142 INFO    MainThread:38356 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 14:08:11,143 INFO    MainThread:38356 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 14:08:11,146 INFO    MainThread:38356 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 14:08:11,367 INFO    MainThread:38356 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 14:08:11,371 INFO    MainThread:38356 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 14:08:11,383 INFO    MainThread:38356 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 14:08:11,386 INFO    MainThread:38356 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 14:08:11,608 INFO    MainThread:38356 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 14:08:11,611 INFO    MainThread:38356 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 14:08:12,944 INFO    MainThread:38356 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 14:08:12,950 INFO    MainThread:38356 [wandb_init.py:_resume_backend():229] resuming backend
2020-11-23 14:08:13,942 INFO    MainThread:38356 [wandb_init.py:_pause_backend():224] pausing backend
2020-11-23 14:08:55,706 INFO    MainThread:38356 [wandb_run.py:_atexit_cleanup():1188] got exitcode: 0
2020-11-23 14:08:55,707 INFO    MainThread:38356 [wandb_run.py:_restore():1160] restore
2020-11-23 14:08:55,710 INFO    MainThread:38356 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "0109cb21c28c408489148eaf3e89016e"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 621
      total_bytes: 621
    }
  }
}

2020-11-23 14:08:57,713 INFO    MainThread:38356 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "c16d18dd7aa7484ca08f117e1b068d15"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 4420
      total_bytes: 4420
    }
  }
}

2020-11-23 14:08:58,784 INFO    MainThread:38356 [wandb_run.py:_show_files():1517] logging synced files
2020-11-23 14:08:58,786 INFO    MainThread:38356 [internal.py:handle_exit():138] Internal process exited
